runtime: custom
api_version: '1.0'
env: flexible
env_variables:
  INAME: "rmcsapi"
liveness_check:
  path: "/ping"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
network:
  instance_tag: rmcsaoi
  name: rmcsapi
  subnetwork_name: default
  session_affinity: true
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.5